--liquibase formatted sql
--changeset fvale:002-add-questions
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Developed in 2009, the name of the popular computer game is "Mine...", what?', 'Shaft', 'Hunter', 'Subsidence', 'Craft', 'D');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'When attacked by predators, which of these animals will often activate a large gland known as an ink sac?', 'Cheetah', 'Squid', 'Owl', 'Cat', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Which of these animal names is also a term often used to refer to a spy?', 'Bull', 'Flea', 'Tiger', 'Mole', 'D');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Complete the saying: "Once in a blue...", what?', 'Moon', 'Star', 'Sky', 'Night', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Who in the TV sitcom "The Big Bang Theory" often uses the catchphrase "Bazinga!"?', 'Leonard', 'Sheldon', 'Howard', 'Raj', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'Which of these numbers also happens to be the sum of two smaller square numbers?', '16', '25', '36', '49', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'In the children''s book series, where is Paddington Bear originally from?', 'India', 'Canada', 'Peru', 'Iceland', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'Which or the following landlocked countries is entirely contained within another country?', 'Lesotho', 'Burkina Faso', 'Mongolia', 'Luxembourg', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'A number one followed by one hundred zeros is known by what name?', 'Googol', 'Megatron', 'Gigabit', 'Nanomole', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'Hannibal crossed the Alps using what animals?', 'Monkeys', 'Elephants', 'Llamas', 'Bears', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Who is credited with inventing the first mass-produced helicopter?', 'Igor Sikorsky', 'Elmer Sperry', 'Ferdinand von Zeppelin', 'Gottlieb Daimler', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which king was married to Eleanor of Aquitaine?', 'Henry I', 'Henry II', 'Richard I', 'Henry V', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Who did artist Grant Wood use as the model for the farmer in his classic painting "American Gothic"?', 'Travelling salesman', 'Local sheriff', 'His dentist', 'His butcher', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'The Norwegian explorer Roald Amundsen reached the South Pole on 14th December of which year?', '1891', '1901', '1911', '1921', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which boxer was famous for striking the gong in the introduction to J. Arthur Rank films?', 'Bombardier Billy Wells', 'Freddie Mills', 'Terry Spinks', 'Don Cockell', 'A');
