--liquibase formatted sql
--changeset fvale:004-add-more-questions
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Which of these names is not in the title of a Shakespeare play?', 'Hamlet', 'Romeo', 'Macbeth', 'Darren', 'D');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'In the United States, what is traditionally the proper way to address a judge?', 'Your holiness', 'Your honor', 'Your eminence', 'Your grace', 'B');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'Which of these pairs of apps offer roughly the same type of service?', 'Snapchat and Grubhub', 'Whatsapp and SHAREit', 'Lyft and Uber', 'TikTok and Spotify', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'If someone asked to see your ID, what might you show them?', 'Your tongue', 'Your teeth', 'Your passport', 'The door', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('E', 'If you''re trying to find other players in a game of hide-and-seek, what are you most likely called?', 'Butterbean', 'Stinky', 'Dunce', 'It', 'D');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'In which of these films does Whoopi Goldberg dress up as a nun?', 'Sister Act', 'Ghost', 'The Color Purple', 'How Judas Got His Groove Back', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'According to a common phrase, a person who takes chances is "going out on a" what?', 'Horse', 'Skateboard', 'Limb', 'Nude beach', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'Due to the geographical areas they represented, the opposing sides of the US Civil War were known by what names?', 'The Hills and the Valleys', 'The Cities and the Farms', 'The North and the South', 'The Kool and the Gang', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'The hammer and sickle is one of the most recognisable symbols of which political ideology?', 'Republicanism', 'Conservatism', 'Liberalism', 'Communism', 'D');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('M', 'Which country holds the title for most Eurovision Song Contest wins?', 'Sweden', 'Norway', 'Ireland', 'United Kingdom', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which country won the 2011 Eurovision Song Contest?', 'Armenia', 'Azerbaijan', 'Georgia', 'Israel', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'The Earth is approximately how many miles away from the Sun?', '9.3 million', '39 million', '93 million', '193 million', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which insect shorted out an early supercomputer and inspired the term "computer bug"?', 'Moth', 'Roach', 'Fly', 'Japanese beetle', 'A');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which of the following men does not have a chemical element named for him?', 'Albert Einstein', 'Niels Bohr', 'Isaac Newton', 'Enrico Fermi', 'C');
insert into question(level, text, option_a, option_b, option_c, option_d, answer) values ('H', 'Which scientific unit is named after an Italian nobleman?', 'Pascal', 'Ohm', 'Hertz', 'Volt', 'D');
